test_modes: test_modes.f90 get_mode.f90 check_norm.f90 intgrl_disc.f90 find_disc.f90
	 gfortran -o test_modes test_modes.f90 check_norm.f90 intgrl_disc.f90 find_disc.f90 get_mode.f90
clean:
	\rm -f test_modes *~ *.o \#*\#
